apiVersion: v1
kind: Service
metadata:
  name: microtask-categories-service
  labels:
    app: microtask-categories-api
    service: microtask-categories-service
spec:
  selector:
    service: microtask-categories-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80